### ISSUE TITLE
about supporting Load MML file

### ISSUE THREAD

**Issue by suzukiplan** [suzukiplan/vgs-bgm-decoder#1]
I'm thinking it will be supported in an another repository (e.g.: vgs-mml-compiler).
Because I want the responsibility of vgs-bgm-decoder to simple.

**Comment by ghost** [comment]
Okay, I will combine them together in my plugin design.

**Comment by suzukiplan** [comment]
https://github.com/suzukiplan/vgs-mml-compiler
