### ISSUE TITLE
Performance Optimizing

### ISSUE THREAD

**Issue by ghost** [suzukiplan/vgs-bgm-decoder#17]
I just profiled the entire plugin using `valgrind` utility and found some performance issues.

After about 1.5 minutes of playback, the function `vgsdec_execute()` only get called 580 times, but the function `set_note()` got called **144974 times** and generated **21,591,256,196 CPU instructions** together. 

That's a big performance issue. Maybe forcing `inline` the `set_note()` function may help? 

I've sent an email of the screenshot of `valgrind` to you, please have a look.

**Comment by suzukiplan** [comment]
> Maybe forcing inline the set_note() function may help?

It's very effective.

### before adding `inline` + -O2 option:

```
$ time valgrind --tool=callgrind ./decoder test.vgs test.wav
~ skip ~
==25647== Events    : Ir
==25647== Collected : 925036265
==25647== 
==25647== I   refs:      925,036,265

real    0m4.540s
user    0m4.274s
sys 0m0.126s
```

### after added `inline` + -O2 option:

```
$ time valgrind --tool=callgrind ./decoder test.vgs test.wav
~ skip ~
==25672== Events    : Ir
==25672== Collected : 356974553
==25672== 
==25672== I   refs:      356,974,553

real    0m2.724s
user    0m2.445s
sys 0m0.167s
```

I'll correct it.
