### ISSUE TITLE
vgsdec_load_vgs_from_file: load .vgs file function

### ISSUE THREAD

**Issue by suzukiplan** [suzukiplan/vgs-bgm-decoder#8]
support loading .vgs format file. (BGM + META data)

**Comment by ghost** [comment]
Will it autodetect whether the input file format is plain BGM or BGM + META?

**Comment by suzukiplan** [comment]
Oh, it's possible.
I will support without adding new function.
thanks

**Comment by ghost** [comment]
My current implementation:

If file extension is `.mml`, convert it to BGM, and pass it to `vgsdec_load_bgm_from_memory()`.
If file extension is `.bgm`, load into memory directly, and pass it to `vgsdec_load_bgm_from_memory()`.

What should I do when opening `.vgs` files? And how to retrieve information from inner META?

**Comment by suzukiplan** [comment]
Same as `.bgm` :
If file extension is `.vgs` , load into memory directly, and pass it to `vgsdec_load_bgm_from_memory()`.

_\* `vgsdec_load_bgm_from_file()` also can be read `.vgs` file._

**Comment by suzukiplan** [comment]
> And how to retrieve information from inner META?

Ah, it's may need new function (vgsdec_get_meta).

**Comment by ghost** [comment]
Okay, got it.
