### ISSUE TITLE
Loop control

### ISSUE THREAD

**Issue by ghost** [suzukiplan/vgs-bgm-decoder#9]
In the mobile Touhou VGS APP, users can:
- see whether the song is `looped` or `acyclic`. 
- If it's a `looped` song, choose repeat times from 1 ~ 3 or infinite.

How to implement similar functionalities using this library?

**Comment by suzukiplan** [comment]
> - see whether the song is looped or acyclic.

get `VGSDEC_REG_LOOP_INDEX`
I described it: https://github.com/suzukiplan/vgs-bgm-decoder/commit/5c408d9a8f134b737cc50cf2eef186747c4fa0cf

> - If it's a looped song, choose repeat times from 1 ~ 3 or infinite.

get `VGSDEC_REG_LOOP_COUNT`
And set `VGSDEC_REG_FADEOUT`, if it was bigger than loop-limit (1 ~ 3).

**Comment by ghost** [comment]
> get VGSDEC_REG_LOOP_COUNT
> And set VGSDEC_REG_FADEOUT, if it was bigger than loop-limit (1 ~ 3).

I mean, give user an option to choose the times the song will be looped.
So can I set `VGSDEC_REG_LOOP_COUNT` to the number of times that I want to loop?
e.g. `vgsdec_set_value(vgs_ctx, VGSDEC_REG_LOOP_COUNT, 5);` makes the song loop 5 times.

**Comment by suzukiplan** [comment]
> the number of times that I want to loop

It should not the responsibility of `vgs-bgm-decoder` side.
For example, Touhou VGS manages it ownself.

_"the number of times that I want to loop"_ of Touhou VGS is here:
- declare: https://github.com/suzukiplan/Touhou-VGS-MML-data/blob/master/game.c#L256
- display: https://github.com/suzukiplan/Touhou-VGS-MML-data/blob/master/game.c#L1107
- check: https://github.com/suzukiplan/Touhou-VGS-MML-data/blob/master/game.c#L1401

**Comment by ghost** [comment]
I see, I will have a look.
